name: Minimal-CI

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

jobs:
  build-cpp-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linux-build
        with: 
          compiler: "gcc"
          config: "Debug"
          version: "latest"

  build-cpp-clang:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linux-build
        with: 
          compiler: "clang"
          config: "Debug"
          version: "latest"

  build-cpp-msvc:
    runs-on: "windows-2022"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/windows-build
        with: 
          config: "Debug"
          version: "latest"

  test-cpp-gcc:
    needs: build-cpp-gcc
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linux-test
        with: 
          build-artifact: build-cpp-linux-gcc-latest-Debug-full

  test-cpp-clang:
    needs: build-cpp-clang
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linux-test
        with: 
          build-artifact: build-cpp-linux-clang-latest-Debug-full

  test-cpp-msvc:
    needs: build-cpp-msvc
    runs-on: "windows-2022"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/windows-test
        with: 
          build-artifact: build-cpp-windows-msvc-latest-Debug-full

  build-py-epidata:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-py
        with:
          package: epidata

  test-py-epidata:
    needs: build-py-epidata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-py
        with: 
          package: epidata
  
  build-py-generation:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-py
        with:
          package: generation

  test-py-generation:
    needs: build-py-generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test-py
        with: 
          package: generation

  build-py-simulation:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-py
        with:
          package: simulation

  test-py-simulation:
    needs: build-py-simulation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-py
        with: 
          package: simulation

  test-pylint-epidata:
    needs: build-py-epidata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-pylint
        with:
          package: epidata
          
  test-docs:
    needs: build-py-epidata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-docs
